### PR TITLE
feat: use confirm() instead of echo

### PR DESCRIPTION
**Pull request by isaksamsten**
Hi!

I use bufdelete and recently started using noice. Unfortunatly, bufdelete does not play nice with notifications etc with noice. This pull-request migrates the confirm dialog to vim.fn.confirm instead of `echo` + `getchar`.

Thanks for an excellent plugin!

### CODE REVIEW

**Comment by isaksamsten** [comment]
Resolves #37

**Comment by famiu** [comment]
Why did you remove the writeln? There was absolutely no relation between that and the rest of the PR. And no, the `writeln` is NOT unnecessary, there is a very good reason for it to be there which is consistency with the built-in `bdelete` and `bwipeout` commands. Please don't make random changes like these on a whim without at least asking about it first, especially when it's completely unrelated to the PR

**Comment by isaksamsten** [comment]
> Why did you remove the writeln? There was absolutely no relation between that and the rest of the PR. And no, the `writeln` is NOT unnecessary, there is a very good reason for it to be there which is consistency with the built-in `bdelete` and `bwipeout` commands. Please don't make random changes like these on a whim without at least asking about it first, especially when it's completely unrelated to the PR

Sorry :-) It was actually a mistake. I intended it for my own workflow not for public consumption and forgot it would propage to the PR.

**Comment by famiu** [comment]
> > Why did you remove the writeln? There was absolutely no relation between that and the rest of the PR. And no, the `writeln` is NOT unnecessary, there is a very good reason for it to be there which is consistency with the built-in `bdelete` and `bwipeout` commands. Please don't make random changes like these on a whim without at least asking about it first, especially when it's completely unrelated to the PR
> 
> Sorry :-) It was actually a mistake. I intended it for my own workflow not for public consumption and forgot it would propage to the PR.

Alright, no problem then 👍🏼
Will test out the PR soon

**Comment by famiu** [comment]
thanks for your contribution :)

**Pull request merged**
